# Copyright 2024 Amazon.com, Inc. or its affiliates. 
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 https://aws.amazon.com/apache-2-0/

region: "${region}"
vpcId: "${vpc_id}"

podDisruptionBudget:
  maxUnavailable: 1

logLevel: "debug"
enableShield: false
enableWaf: false
enableWafv2: false

image:
  repository: "${aws_htc_ecr}/ecr-public/eks/aws-load-balancer-controller"

nodeSelector:
  htc/node-type: "core"

tolerations:
  - key: "htc/node-type"
    operator: "Equal"
    value: "core"
    effect: "NoSchedule"
